### ISSUE TITLE
[Suggestion] ox_core compatability

### ISSUE THREAD

**Issue by paruthepro** [Byte-Labs-Project/bl_bridge#11]
Despite ox_cores current development stage, it is still utilised by a few of us for our personal projects and even full scale servers, it would great if this could be added as a support framework given that eventually ox_core will become quite the substantial and well developed framework, would be great to get ahead of the curve.

**Comment by Frowmza** [comment]
Yeah, I didn't want to add it because it's going to be rewritten. I really don't want to waste time doing it when I'll have to edit it later.
