### ISSUE TITLE
error

### ISSUE THREAD

**Issue by WALKERIS** [Byte-Labs-Project/bl_bridge#6]
![image](https://github.com/Byte-Labs-Project/bl_bridge/assets/123303978/55d57dce-d5ce-4460-bd81-1b36f3c2f644)
error with bl_customs when adding job to it

**Comment by Frowmza** [comment]
which esx version you using?

**Comment by DesertCryso** [comment]
By the picture, he is using esx legacy. The same as me and i have the exact same issue.

**Comment by WALKERIS** [comment]
> which esx version you using?

im using 10.2 esx legacy

**Comment by Frowmza** [comment]
this fixed!
